# ğŸ“‚ wrangler.toml

name = "telegram-bot-worker"    # Ø§Ø³Ù… Ù¾Ø±ÙˆÚ˜Ù‡
main = "src/index.js"           # ÙØ§ÛŒÙ„ ÙˆØ±ÙˆØ¯ÛŒ Ø±Ø¨Ø§Øª
compatibility_date = "2025-08-31"  # ØªØ§Ø±ÛŒØ® Ø«Ø§Ø¨Øª Ø¨Ø±Ø§ÛŒ API Cloudflare
compatibility_flags = ["nodejs_compat"] # ÙØ¹Ø§Ù„ Ú©Ø±Ø¯Ù† Ø³Ø§Ø²Ú¯Ø§Ø±ÛŒ Ø¨Ø§ Ø¨Ø®Ø´ÛŒ Ø§Ø² Node API

[vars]
BOT_TOKEN = "7420115590:AAHoGQZd5Lcb_oI3FTHomIQJHIsFNTZA2dM"   # Ù…ÛŒØ´Ù‡ Ø§Ø² wrangler secret Ù‡Ù… Ø§Ø³ØªÙØ§Ø¯Ù‡ Ú©Ø±Ø¯
CURRENCY_LIST = '["usdt","btc","bome"]'
TELEGRAM_CHAT_ID = "6295512279"



[triggers]
crons = ["*/1 * * * *"]